server:
  port: 8082
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ticketdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2console/