server:
  port: 8082
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ticketdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2console/

  main:
    allow-bean-definition-overriding: true
custom:
  external-api:
    get_all_emp: http://localhost:8081/emp
    get_emp_by_id: http://localhost:8081/employee/{eid}
    add_emp: http://localhost:8081/addEmp